name: CI

on:
  push:
    branches:
      - main
      - feature/add-logging-and-genre-support
  pull_request:
    branches:
      - main
      - feature/add-logging-and-genre-support

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Clear Python package cache
      run: |
        pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installation
      run: |
        pip list
        python -c "import matplotlib.pyplot as plt; print('matplotlib installed successfully')"

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/video-generating-agent/video-generating-agent/nonrigid_nerf" >> $GITHUB_ENV

    - name: Download pre-trained model
      run: |
        chmod +x download_model.sh
        ./download_model.sh

    - name: Verify model download
      run: |
        if [ -f "models/RealESRGANv2-animevideo-xsx4.pth" ]; then
          echo "Model file exists."
        else
          echo "Model file does not exist."
          exit 1
        fi

    - name: Install Kaggle CLI
      run: |
        pip install kaggle

    - name: Download dataset from Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        kaggle datasets download -d sauravmaheshkar/nerf-dataset -p preprocessed_data --unzip
        if [ -d "preprocessed_data/nerf_llff_data" ] || [ -d "preprocessed_data/nerf_real_360" ] || [ -d "preprocessed_data/nerf_synthetic" ]; then
          echo "Dataset directories exist."
        else
          echo "Dataset directories do not exist."
          exit 1
        fi

    - name: List contents of preprocessed_data directory after download
      run: |
        ls preprocessed_data

    - name: Wait for dataset extraction
      run: |
        sleep 60

    - name: Verify dataset download
      run: |
        if [ -d "preprocessed_data/nerf_llff_data" ] || [ -d "preprocessed_data/nerf_real_360" ] || [ -d "preprocessed_data/nerf_synthetic" ]; then
          echo "Dataset directories exist and are not empty."
        else
          echo "Dataset directories do not exist or are empty."
          exit 1
        fi

    - name: List contents of preprocessed_data directory
      run: |
        ls preprocessed_data

    - name: List contents of nerf_llff_data directory
      run: |
        ls preprocessed_data/nerf_llff_data

    - name: List contents of nerf_real_360 directory
      run: |
        ls preprocessed_data/nerf_real_360

    - name: List contents of nerf_synthetic directory
      run: |
        ls preprocessed_data/nerf_synthetic

    - name: Verify presence of image files in nerf_llff_data directory
      run: |
        if ls preprocessed_data/nerf_llff_data/*.png 1> /dev/null 2>&1; then
          echo "Image files exist in nerf_llff_data directory."
        else
          echo "Image files do not exist in nerf_llff_data directory."
          exit 1
        fi

    - name: Train model
      run: |
        python nonrigid_nerf/train.py --config nonrigid_nerf/configs/training_config.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests
