name: CI

on:
  push:
    branches:
      - main
      - feature/add-logging-and-genre-support
  pull_request:
    branches:
      - main
      - feature/add-logging-and-genre-support

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Clear Python package cache
      run: |
        pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installation
      run: |
        pip list
        python -c "import matplotlib.pyplot as plt; print('matplotlib installed successfully')"

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/video-generating-agent/video-generating-agent/nonrigid_nerf" >> $GITHUB_ENV

    - name: Run tests
      run: |
        python -m unittest discover -s tests
